@startuml
class  mastermind.ConsoleMasterMind{
+ {static} main(String[]): void
# createView(): View
}
mastermind.MasterMind <|-down- mastermind.ConsoleMasterMind

class  mastermind.GraphicsMasterMind{
+ {static} main(String[]): void
# createView(): View
}
mastermind.MasterMind <|-down- mastermind.GraphicsMasterMind

class  mastermind.MasterMind{
- logic: Logic
- view: View
# MasterMind()
# {abstract} createView(): View
# play(): void
}
mastermind.MasterMind --> mastermind.views.View
mastermind.MasterMind *-down-> mastermind.controllers.Logic
@enduml